name: Create profile readme

on:
  # Trigger the workflow on push
  push:
    # Every branch
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-profile-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Upgrade package installer for Python
        run: python -m pip install --upgrade pip

      - name: Install Python dependencies
        run: python -m pip install pyyaml

      - name: Create profile/README.md from profile/README.yaml
        run: python tools/create_profile_readme.py

      - name: Push changes to the repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add profile/README.md
          git commit -m "Create profile/README.md from profile/README.yaml"
          git push
